### ISSUE TITLE
Won't install via Alcatraz in Xcode  7.3.1

### ISSUE THREAD

**Issue by barnaclejive** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#1]
The install progress bar starts but then backs off and stops. I have tried restarting and clearing the global derived data. I have the latest Alcatraz version (1.1.18) installed in Xcode 7.3.1 (7D1014).

**Comment by bigsprocket** [comment]
Same here. Console output:

```
5/6/16 10:15:24.348 AM Xcode[33098]: Updating Repo: /Users/kyle/Library/Application Support/Alcatraz/Plug-ins/Build Time Analyzer for Swift
5/6/16 10:15:24.641 AM Xcode[33098]: Git fetch output: 
5/6/16 10:15:24.646 AM Xcode[33098]: Git reset output: HEAD is now at 798fd14 Update README.md
5/6/16 10:15:24.651 AM Xcode[33098]: Wasn't able to find: Build Time Analyzer for Swift.xcodeproj in /Users/kyle/Library/Application Support/Alcatraz/Plug-ins/Build Time Analyzer for Swift
```

**Comment by RobertGummesson** [comment]
Ah, didn't realize 7.3.1 was out. Will update and fix this. Give me a moment.

**Comment by RobertGummesson** [comment]
Ok. So the plug-in compatibility UUID is the same in 7.3.1 as in 7.3. In other words, it should work. Could you try building the plug-in yourselves and see if that works, @barnaclejive / @bigsprocket ?

1) Download or clone it
2) Open it in Xcode and do a build
3) Restart Xcode and see if Build Time Analyzer shows up at the bottom of the View menu.

**Comment by krusek** [comment]
Doesn't work from alcatraz for me either, but I'll give your steps a try.

**Comment by krusek** [comment]
That appears to work.

**Comment by RobertGummesson** [comment]
@krusek  Great. I'll make a note of that in the read me file. Will try from Alcatraz later and see what's going on.

**Comment by barnaclejive** [comment]
@RobertGummesson - manual build/install worked for me also. Thanks for the cool plugin, I found it via the iosdevweekly newletter today. Good luck on the Alcatraz fix.

**Comment by NachoSoto** [comment]
Looks like this is the problem:
> 5/6/16 10:15:24.651 AM Xcode[33098]: Wasn't able to find: `Build Time Analyzer for Swift.xcodeproj` in /Users/kyle/Library/Application Support/Alcatraz/Plug-ins/Build Time Analyzer for Swift

But the project name in there has no spaces:
<img width="769" alt="screen shot 2016-05-06 at 10 24 45 am" src="https://cloud.githubusercontent.com/assets/685609/15080841/c6d742a0-1374-11e6-9156-68ef8af13a7c.png">

**Comment by RobertGummesson** [comment]
@NachoSoto Good stuff. Have created a pull request with a fix for this.

**Comment by onmyway133** [comment]
For now, I install all the plugins via manually building the projects 🎉

**Comment by RobertGummesson** [comment]
It's now working to install from Alcatraz again. May be worth while to get the latest build in case you installed before the 'go to line' stuff made it to master.
