### ISSUE TITLE
Obj-C Support?

### ISSUE THREAD

**Issue by sethfri** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#13]
Is there support planned for Obj-C? It would be great to see why compilation is taking so long in a large, Obj-C based project. Does this project rely on anything Swift specific?

**Comment by RobertGummesson** [comment]
The issue here is that the flags added to the Build Settings are Swift specific. I'm not sure if Xcode offers equivalent flags for Obj-C. If you would find equivalent flags however, the plug-in would likely work without code changes.
