### ISSUE TITLE
possible enhancement to print the result to log file 

### ISSUE THREAD

**Issue by steve21124** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#16]

**Comment by steve21124** [comment]
by the way, using the logger from https://thatthinginswift.com/debug-long-compile-times-swift/

and your BuildTimeAnalyzer seems like the compile time did not match

**Comment by RobertGummesson** [comment]
They will match if you compare the same log files (and not two separate builds). How did you make the comparison?

**Comment by steve21124** [comment]
by do sorting | egrep '\.[0-9]ms' | sort -t "." -k 1 -n | tail -10.......

however, second look, there are multiple methods inside one class in separate line. probably because of that one, the numbers are off. ....

fyi: there is another performance report
https://github.com/tumblr/SwiftCompilationPerformanceReporter
