### ISSUE TITLE
Plugin suggestions to improve build times

### ISSUE THREAD

**Issue by nobre84** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#19]
The plugin currently only shows the method/line that is taking too long. Could it have some insight on what exactly is causing the slowdown and suggestions for improvement ?

**Comment by RobertGummesson** [comment]
I'm afraid I won't be able to make the plug-in that intelligent. Apple does not expose why the compiler is confused to us mortals so we have to rule it out ourselves line by line. :(
