### ISSUE TITLE
Check Cocoapods pod compile time

### ISSUE THREAD

**Issue by dmorrow** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#24]
Is it possible to use this plugin to check compile time for any Cocoapods included in the project?

**Comment by RobertGummesson** [comment]
Assuming the CocoaPoda are built in Swift (and not a compiled framework), I can't see why it wouldn't work already. Having that said, I actually haven't tried any and all projects I work on uses CocoaPods built in Objective-C or C.

If they are not coded in Swift however, it won't work. The plugin relies on the 'debug time function bodies' flag which is only works for Swift.

**Comment by plivesey** [comment]
@dmorrow, you can add something like this to your Podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        s = config.build_settings['OTHER_SWIFT_FLAGS']
        s = [ '\$(inherited)' ] if s == nil;
        s.push('-Xfrontend')
        s.push('-debug-time-function-bodies')
        config.build_settings['OTHER_SWIFT_FLAGS'] = s
      end
    end
end
```

**Comment by Buju77** [comment]
@plivesey thx for the suggestion.

It has one slight typo though. You don't need the `\` to escape if the string is using single-quoted `'` in Ruby.

> 
> ```
>         ...
>         s = [ '$(inherited)' ] if s.nil?
>         ...
> ```
