### ISSUE TITLE
Build times should be cumulative

### ISSUE THREAD

**Issue by eaigner** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#26]
Sometimes files show up multiple times with different build times. I suppose this is because of target dependencies. It would be nice if identical lines would be grouped and their cumulative build time displayed.

**Comment by RobertGummesson** [comment]
> Sometimes files show up multiple times with different build times. I suppose this is because of target dependencies.

The plugin displays build times for functions rather than files (see the Function column). That would be why you see the same file show up multiple times.

**Comment by eaigner** [comment]
No. It's the same function AND same file.

**Comment by RobertGummesson** [comment]
Ah, that would be a bug. I haven't actually seen this for any of my projects. Let me see if I am able to reproduce this when I have a moment.

If you have then time and able to build the plugin yourself, it would be interesting to see if that goes away if:
`return time.hashValue ^ text.hashValue`
is swapped to:
`return text.hashValue`
in CMRawMeasure.swift.

**Comment by eaigner** [comment]
Example screenshot

![screen shot 2016-05-23 at 12 19 04](https://cloud.githubusercontent.com/assets/112197/15467798/a1f56e98-20e0-11e6-90b0-ec838f2d237d.png)

**Comment by eaigner** [comment]
Let me check

**Comment by eaigner** [comment]
By the way. Is there a reason the results are capped at 20?

**Comment by RobertGummesson** [comment]
I added it for performance reasons but never benchmarked it. It could likely be increased.

**Comment by RobertGummesson** [comment]
Thanks for this find and your commits. Have merged the branch to master...
