### ISSUE TITLE
How to make the window topmost only for Xcode

### ISSUE THREAD

**Issue by RobertGummesson** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#3]
GIVEN the plug-in window is showing
WHEN Xcode is minimized
THEN (expected) the window should no longer be on top
THEN (currently) the window is on top

The window should remain on top as long as Xcode is opened though. Couldn't quite figure out how to do this. (I'm an iOS dev, not really an OSX dev). 😜

**Comment by ed-mejia** [comment]
+1

**Comment by RobertGummesson** [comment]
Closing this one since [#45](https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode/pulls) will turn this into a standalone app.
