### ISSUE TITLE
Xcode 8 support

### ISSUE THREAD

**Issue by RobertGummesson** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#38]
Starting with Xcode 8, plugins will no longer be supported. I will make an attempt to work around this by making the Build Time Analyzer a standalone app. I believe this can be done by simply scanning the log files during the app launch (and perhaps with a refresh button or similar). 

The most recent log file / files will be the ones to work with.

**Comment by onmyway133** [comment]
@RobertGummesson or we can add a new run script build phase, and trigger the standalone app from there

**Comment by RobertGummesson** [comment]
@onmyway133 - Yep, that's an option too. ...or perhaps both.

**Comment by orta** [comment]
I have a build log parser here: https://github.com/orta/Snapshots-app/blob/master/Snapshots/DeveloperDirWatcher.swift

Been wanting to convert all of this stuff into an XcodeSDK mixed with the new AppleScript API, but haven't made the time yet.

**Comment by RobertGummesson** [comment]
@orta Good stuff

**Comment by juliand665** [comment]
Is there any progress on Xcode 8 support? I'd love to use this!

**Comment by RobertGummesson** [comment]
Yes, but it's been slow (other priorities). I'm still on it though so bare with me. :)

**Comment by RobertGummesson** [comment]
Update:  [#45](https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode/pull/45) contains the implementation for the standalone app. I will be testing it throughout the day and merge it to master if nothing catches on fire.

A standalone app is obviously a bit more limited than a plug-in. Basically, the app now monitors the derived data folder rather than subscribing to Xcode notifications. Here are a couple of limitations:
- The app doesn't indicate when a build process has started (but it knows when it ends)
- Jumping to line upon selection no longer works, instead it just opens up the appropriate Swift file.

I have also made some smaller improvements. One is the ability to choose existing projects to analyze, i.e existing builds.
