### ISSUE TITLE
Build Error on XCode 7.2, swift 2.1.1

### ISSUE THREAD

**Issue by cakl** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#44]
An error occurs at CMXcodeWorkspace.swift L126: Instance member valueForKey cannot be used on type AnyObject:

`
    private static  func workspaceWindowControllers() -> [AnyObject]? {
        guard let windowController = NSClassFromString("IDEWorkspaceWindowController") else { return nil }
        return windowController.valueForKey("workspaceWindowControllers") as? [AnyObject]
    }
`

XCode 7.2, Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)

**Comment by RobertGummesson** [comment]
Hmmm... I haven't seen or heard about that issue before. On Xcode 7.3.1 it compiles just fine. Is upgrading your Xcode an option?

**Comment by RobertGummesson** [comment]
Closing this one since [#45](https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode/pulls) will turn this into a standalone app. I will not longer maintain the plug-in.
