### ISSUE TITLE
Xcode 8 standalone app Not opening

### ISSUE THREAD

**Issue by hardikdevios** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#47]
1) Clone and run.
2) I have followed the instruction based on main screen.
3) Build succeed but nothing is getting Updated on Main screen, its just the same old screen with instructions steps.

**Comment by RobertGummesson** [comment]
Two things to check:
- Is the derived data path at the bottom of the screen correct?
- Are you able to see and select any projects in the project selection window? (the window above the derived data path field)

**Comment by hardikdevios** [comment]
I have solved now looks like its not taking the correct path 

**1) Changes in Code** 
![screen shot 2016-09-26 at 5 03 35 pm](https://cloud.githubusercontent.com/assets/6657591/18832839/376aac44-840b-11e6-9c06-549f1888c0cf.png)

**Because Even changing derived location doesn't appear projects in above box in the App so i have change some code as above** 
![screen shot 2016-09-26 at 5 07 26 pm](https://cloud.githubusercontent.com/assets/6657591/18832949/e03744c2-840b-11e6-8a2c-49433570988b.png)

**2) Its crashing when ever clicking on empty section , workaround**


![screen shot 2016-09-26 at 5 12 59 pm](https://cloud.githubusercontent.com/assets/6657591/18833162/00e1b30a-840d-11e6-9deb-a88c84622515.png)


Thanks man

**Comment by RobertGummesson** [comment]
Thanks for the info. I will fix this.

**Comment by RobertGummesson** [comment]
Fixed. Should work now if you build from master.
