### ISSUE TITLE
How to analyze a pod?

### ISSUE THREAD

**Issue by ileitch** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#49]
We have two apps and a library which we share between the two as a cocoapod. Reporting works great for the apps themselves, but I'd like for them to include the compile times of the shared pod. Any idea how to achieve this?

Great little utility btw 👍🏼

**Comment by RobertGummesson** [comment]
That's a good question. I haven't tried to analyze pods and am uncertain if those can be included in the log files. Worst case, you will need to analyze the shared project separately.

**Comment by ileitch** [comment]
Our shared project has its own app just for a few demonstrative purposes, but the code of value is all in library form. I think the problem is that the compiler flags are set on a target, yet the code in the shared pod is not directly part of any runnable target.

**Comment by RobertGummesson** [comment]
On a different note though, is your library [pre-compiled](http://stackoverflow.com/questions/23117574/publishing-a-precompiled-cocoapod)? 

If you're having problems with long running build times, it may seem a bit unnecessary to recompile the framework each time. Particularly if the project is maintained separately.
