### ISSUE TITLE
Window disappears once minimized

### ISSUE THREAD

**Issue by deepumukundan** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#53]
Once the window is minimized to dock or somehow gets hidden, it never comes back. The workaround is to quit and restart BuildTimeAnalyzer.

Happens on
OS: 10.11.6 OSX El Capitan
BuildTimeAnalyzer 1.0.2

**Comment by RobertGummesson** [comment]
That's odd. Works fine for me (on 10.12.1 OSX El Capitan). Will probably need help on debugging this.

**Comment by deepumukundan** [comment]
Sure. Let me know how I can help. I do iOS dev, but I can give it a shot on the mac app. Will the console logs help? Or do you have pointers to any specific file or method where I can look at? This could be even an OS thing. I can give it a shot on my Sierra laptop.

**Comment by RobertGummesson** [comment]
I'm an iOS dev too and was lost half the time I developed this so no worries there. ;)

**Comment by normand1** [comment]
I'm on 10.11.6 and it works ok for me. The only oddity is that I can't command+tab back to it. I need to click on it in the tray to get it to come to the foreground again.

**Comment by RobertGummesson** [comment]
@normand1 - If you disable "Always in Front" under the window menu, that should work as expected again. 

The app is always in front by default which is similar to how it worked when it was still an Xcode plug-in.

**Comment by deepumukundan** [comment]
Sorry this fell off my Radar. So windows programming guide on macOS states we need to reset the level when window is hidden. https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Concepts/WindowLevel.html

I will create a PR to set/reset this on view lifecycle changes. First ever mac app code change. Should be fun!

**Comment by RobertGummesson** [comment]
Thanks @deepumukundan
