### ISSUE TITLE
How to analyse a ObjC and Swift app?

### ISSUE THREAD

**Issue by Ricardo1980** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#55]
Hello!

My app is not 100% Swift. It is 90% ObjC and 10% Swift.
Can I use this plugin or is there anything I could do?

Thanks.

**Comment by RobertGummesson** [comment]
Hi @Ricardo1980 

No, the analyzer only supports Swift. You can use it, but it will only analyze your Swift files. I'm not aware of anything similar for Obj-C but that's not to say there isn't anything out there. The Obj-C compiler has been around for a long time and doesn't come with the same performance hick-ups as the Swift compiler.
