### ISSUE TITLE
Run as script for testing

### ISSUE THREAD

**Issue by gsabran** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#58]
I'd like to integrate the time analyser with my test to ensure that no function is taking too long to compile. Is there a way to do so?

Thanks for this amazing project

**Comment by RobertGummesson** [comment]
Not currently but I'd be open to contributions to add it. If you are using CI, perhaps [xcprofiler](https://github.com/giginet/xcprofiler) would solve the problem? Not sure if that uses cumulative time though.
