### ISSUE TITLE
Issue building on Xcode 9 beta 5

### ISSUE THREAD

**Issue by mark-anders** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#68]
Sorry to ask the most obvious question, but I can't figure out what to open.  I followed the instructions and added the flag and rebuilt.  However, clicking the button to the right of the Derived Data Location simply brings me to a Finder Window showing the Derived Data folder in my Library.  I'm not sure what to do from that point.  Since it's not a file open dialog, if I do anything in Finder window, nothing happens. I have pasted the path to some file - though I'm not sure what type of file is needed, but then what?  Nothing seems to happen.

Btw, I'm using this with Xcode 9 Beta 5.

**Comment by RobertGummesson** [comment]
You don't have to open anything. If you've added the Swift compiler flags correctly, cleaned your project and rebuilt, the Analyzer will display the build times after Xcode has finished building automatically.

If that would fail, you can choose the project by clicking its name in the lower window. I haven't tried it in Xcode 9 beta 5 yet, but it works fine in Xcode 9 beta 4.

**Comment by mark-anders** [comment]
Retried it with a few other projects and nothing happens for me.  I'm also on macOS 10.13

**Comment by RobertGummesson** [comment]
How far do you get? Do you see a list of projects when you open the app. If not, have you changed the default location of the derived data location?

You should get an error if the log files are missing or invalid. Have you seen one?

**Comment by mark-anders** [comment]
Ok, problem solved! The issue was that I built BuildTimeAnalyzer using Xcode 9 Beta 5.  I rebuilt using Xcode 8.3 and suddenly see a list of previously builds.

**Comment by RobertGummesson** [comment]
Great. Glad it worked.
