### ISSUE TITLE
Getting lots of error while tries to run.

### ISSUE THREAD

**Issue by RPiyush** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#74]
I downloaded code, and tries to run it gives me error for 
**'Use Legacy Swift Language version'** which earlier was **Unspecified**. I changed to No for Swift 3.0 then I got errors.

Any Help Appreciated. Thanks

**Comment by RobertGummesson** [comment]
What Xcode version are you using?

**Comment by igorkislyuk** [comment]
Also got a lot of warnings. Version Xcode 9.1
Seems that flag are no more valid.

**Comment by RobertGummesson** [comment]
What warnings do you get? I'm on Xcode 9.1 too and I get no warnings when I build the project. I also tried on Xcode 9.2 beta and it's fine there too.

**Comment by igorkislyuk** [comment]
@RobertGummesson  Hi, I get simple error - "Failed to parse logs". Otherwise, **computer restart helped me**. Thank you. We can close this issue?

**Comment by RobertGummesson** [comment]
@RPiyush - Do you still have this problem?
