### ISSUE TITLE
Window stays in the foreground

### ISSUE THREAD

**Issue by mathaeus** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#75]
The app window stays in the foreground even when not active. That is rather annoying :-)

**Comment by mathaeus** [comment]
Can be adjusted in the `Window` settings of course. Nonetheless it's not common that this is the default behaviour.

**Comment by RobertGummesson** [comment]
Yes, Built Time Analyzer used to be an Xcode plug-in and the problem would then be that every time you tapped a method name, Xcode's editor foregrounded and it was difficult to find the plug-in window again. I suppose the default could be the other way around now.

**Comment by RobertGummesson** [comment]
#77 solved this
