### ISSUE TITLE
Project doesn't compile in older Xcode versions

### ISSUE THREAD

**Issue by JIACCOPU-ford** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#86]
There is a function reference that doesn't exist

**Comment by RobertGummesson** [comment]
It builds fine for me. What is the missing function?

**Comment by ovidiulaz7** [comment]
same issue here..

<img width="1136" alt="screen shot 2018-04-12 at 23 02 53" src="https://user-images.githubusercontent.com/10559321/38701133-c1a1bca8-3ea5-11e8-85d4-6842db902bfa.png">

**Comment by RobertGummesson** [comment]
Right, this is Swift 4.1 code. If you upgrade to the latest Xcode, this will compile.

**Comment by JIACCOPU-ford** [comment]
I see CI passes now, so it can be colsed.
