### ISSUE TITLE
frequently crash on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by coderxdotwang** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#95]
issue report:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/14144242/63149943-1a181c00-c038-11e9-91ea-2b1976438473.png">

**Comment by RobertGummesson** [comment]
Hmmm... Not a particularly useful crash report. Segmentation fault 11 is Apple's way of saying "No idea what just happened". 

When do you get this? Just right after you launch it or when you are processing a log?

**Comment by coderxdotwang** [comment]
emmm.. it`s the only report presented, only happens when processiong a log，should I always use the tool by running this project in Xcode，or acrhive -> install and launch the BuildTimeAnalyzer.app（now in this way）?

**Comment by RobertGummesson** [comment]
It shouldn't matter if you archive or run it directly from Xcode. I just tried it myself and it didn't crash for me. I am on macOS Catalina though.

Given that you can reproduce the crash, are you able to do some debugging on your own?

**Comment by coderxdotwang** [comment]
yeah, I forgot that I can debug it myself，will have a try tomorrow 😪

**Comment by coderxdotwang** [comment]
after about 10 attempts(quit Xcode -> delete DerivedData -> reopen Xcode -> clean Project / modify some codes -> build -> open Analyzer and process log), no lucky there, In fact, I can't reproduce the crash anymore in both way.
is there any relation to the project/log status? as I fixed the top issuses listed by the analyzer in the past fewew days.
